# Generated by Django 4.1 on 2022-08-30 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='details',
            options={},
        ),
    ]
